Admin patch updated.
I-PMAN/DBMS_Project pull request #8
Opened 2020-12-26 11:10 UTC by I-PMAN

2020-12-26 11:19 UTC, shreyask22 requested changes

2020-12-26 11:19 UTC, shreyask22 commented on UserLogQ.php
>  require "dbcon.php";
I think session_start(); is needed here. I do not know if it works fine without that

2020-12-26 11:26 UTC, I-PMAN commented on UserLogQ.php
>  require "dbcon.php";
Changes made.

2020-12-26 16:12 UTC, shreyask22 approved these changes

2020-12-27 05:38 UTC, shreyask22 requested changes
AddMovieQ has incorrect code

2020-12-27 07:05 UTC, shreyask22 approved these changes

2020-12-27 07:06 UTC, shreyask22 approved these changes

2020-12-27 07:07 UTC, merged